#ifndef _H_CUBEC_ENGINE_TYPE_KIND_
#define _H_CUBEC_ENGINE_TYPE_KIND_
#ifdef __cplusplus
extern "C" {
#endif
typedef enum _cubec_type_kind_t {
  CUBEC_TYPE_KIND_INT8,
  CUBEC_TYPE_KIND_INT16,
  CUBEC_TYPE_KIND_INT32,
  CUBEC_TYPE_KIND_INT64,
  CUBEC_TYPE_KIND_UINT8,
  CUBEC_TYPE_KIND_UINT16,
  CUBEC_TYPE_KIND_UINT32,
  CUBEC_TYPE_KIND_UINT64,
  CUBEC_TYPE_KIND_FLOAT32,
  CUBEC_TYPE_KIND_FLOAT64,
  CUBEC_TYPE_KIND_BOOLEAN,
  CUBEC_TYPE_KIND_STR,
  CUBEC_TYPE_KIND_POINTER,
  CUBEC_TYPE_KIND_STRUCT,
  CUBEC_TYPE_KIND_UNION,
  CUBEC_TYPE_KIND_REF,
  CUBEC_TYPE_KIND_ENUM,
  CUBEC_TYPE_KIND_ARRAY,
  CUBEC_TYPE_KIND_INTERFACE,
} cubec_type_kind_t;
#ifdef __cplusplus
}
#endif
#endif