#include "engine/integer_type.h"
#include "engine/value.h"
#include "engine/vm.h"
#include "engine/scope.h"
#include "engine/error_type.h"
#include "engine/void_type.h"
#include "engine/bool_type.h"
#include "engine/str_type.h"
#include "engine/type.h"
#include <stdbool.h>
#include <string.h>
#include <stdint.h>
#include <stdio.h>

/* Helper: create a value and register it in vm's current scope */
static value_t _int_value_create(vm_t vm, type_t type, void *data, bool own) {
  value_t v = value_create(vm_get_allocator(vm), type, data, own);
  scope_t scope = vm_get_current_scope(vm);
  if (scope) { vec_push(scope->values, v); }
  return v;
}

/* ---- Integer kind classification ---- */

static bool _is_signed_kind(type_kind_t kind) {
  return kind == TYPE_KIND_I8  || kind == TYPE_KIND_I16 ||
         kind == TYPE_KIND_I32 || kind == TYPE_KIND_I64;
}

static bool _is_unsigned_kind(type_kind_t kind) {
  return kind == TYPE_KIND_U8  || kind == TYPE_KIND_U16 ||
         kind == TYPE_KIND_U32 || kind == TYPE_KIND_U64;
}

static bool _is_integer_kind(type_kind_t kind) {
  return _is_signed_kind(kind) || _is_unsigned_kind(kind);
}

/* ---- Read/write values as uint64_t (preserves all bits) ---- */

static uint64_t _int_read_u64(value_t v) {
  type_t t = value_get_type(v);
  switch (t->size) {
    case 1: return (uint64_t)(*(uint8_t *)value_get_data(v));
    case 2: return (uint64_t)(*(uint16_t *)value_get_data(v));
    case 4: return (uint64_t)(*(uint32_t *)value_get_data(v));
    case 8: return *(uint64_t *)value_get_data(v);
    default: return 0;
  }
}

static void _int_write_u64(type_t t, void *data, uint64_t val) {
  switch (t->size) {
    case 1: *(uint8_t  *)data = (uint8_t)val;  break;
    case 2: *(uint16_t *)data = (uint16_t)val; break;
    case 4: *(uint32_t *)data = (uint32_t)val; break;
    case 8: *(uint64_t *)data = val;             break;
    default: break;
  }
}

static value_t _int_alloc_result(vm_t vm, type_t type, uint64_t val) {
  void *data = allocator_alloc(vm_get_allocator(vm), type->size);
  _int_write_u64(type, data, val);
  return _int_value_create(vm, type, data, true);
}

/* ---- Integer type promotion ---- */

static bool _is_signed_type(type_t t) { return _is_signed_kind(t->kind); }

/**
 * @brief Pick the common type for binary integer operation.
 *
 * Rules (matching C usual arithmetic conversions):
 *  1. Same signedness → larger size wins
 *  2. Different signedness, different size → larger size wins
 *  3. Different signedness, same size → unsigned wins
 */
static type_t _int_common_type(type_t ta, type_t tb) {
  if (ta->size > tb->size) return ta;
  if (tb->size > ta->size) return tb;
  /* same size → unsigned wins */
  return _is_signed_type(ta) ? tb : ta;
}

/**
 * @brief Coerce an integer value to a target integer type (bit-pattern preserving).
 * Used internally for type promotion. Not the same as safe_cast.
 */
static value_t _int_coerce(vm_t vm, value_t v, type_t to) {
  if (value_get_type(v) == to) return v;
  if (value_is_shadow(v))
    return vm_create_value_shadow(vm, to, NULL, true);
  uint64_t val = _int_read_u64(v);
  return _int_alloc_result(vm, to, val);
}

/**
 * @brief Promote two integer operands to a common type.
 * Returns the common type, or NULL if either operand is not an integer kind.
 * Stores coerced operands in *out_a, *out_b.
 */
static type_t _int_promote(vm_t vm, value_t a, value_t b,
                           value_t *out_a, value_t *out_b) {
  type_t ta = value_get_type(a);
  type_t tb = value_get_type(b);
  if (!_is_integer_kind(ta->kind) || !_is_integer_kind(tb->kind))
    return NULL;
  type_t rt = _int_common_type(ta, tb);
  *out_a = _int_coerce(vm, a, rt);
  *out_b = _int_coerce(vm, b, rt);
  return rt;
}

static value_t _int_check_zero(vm_t vm, value_t b) {
  if (_int_read_u64(b) == 0)
    return create_error_value(vm, "division by zero");
  return NULL;
}

/* ---- Shared clone for all integer types ---- */

static value_t _int_clone(vm_t vm, value_t self) {
  if (value_is_shadow(self))
    return vm_create_value_shadow(vm, value_get_type(self), NULL, false);
  type_t t = value_get_type(self);
  void *data = allocator_alloc(vm_get_allocator(vm), t->size);
  memcpy(data, value_get_data(self), t->size);
  return _int_value_create(vm, t, data, true);
}

/* ==================================================================
 * Per-type equal/type_equal/type_extends/safe_cast/assignment
 * Generated by macros — these are type-specific.
 * ================================================================== */

#define DEFINE_SINT_VTABLE(Prefix, ctype, KIND, SIZE, ALIGN, NAME)            \
                                                                               \
static value_t _##Prefix##_equal(vm_t vm, value_t a, value_t b) {             \
  type_t ta = value_get_type(a);                                               \
  type_t tb = value_get_type(b);                                               \
  if (!_is_integer_kind(tb->kind))                                             \
    return create_error_value(vm, "cannot compare values of different kinds");  \
  if (value_is_shadow(a) || value_is_shadow(b)) {                              \
    type_t rt = _int_common_type(ta, tb);                                      \
    return vm_create_value_shadow(vm, rt, NULL, true);                         \
  }                                                                            \
  value_t pa, pb;                                                              \
  type_t rt = _int_promote(vm, a, b, &pa, &pb);                               \
  if (!rt) return create_error_value(vm, "integer comparison failed");         \
  return create_bool_value(vm, _int_read_u64(pa) == _int_read_u64(pb));       \
}                                                                              \
                                                                               \
static value_t _##Prefix##_type_equal(vm_t vm, type_t a, type_t b) {          \
  (void)a;                                                                     \
  if (b->kind == TYPE_KIND_WILDCARD)                                           \
    return create_bool_value(vm, true);                                        \
  return create_bool_value(vm, b->kind == KIND);                              \
}                                                                               \
                                                                               \
static value_t _##Prefix##_type_extends(vm_t vm, type_t sub, type_t super) {  \
  (void)sub;                                                                   \
  if (super->kind == TYPE_KIND_WILDCARD)                                       \
    return create_bool_value(vm, true);                                        \
  return create_bool_value(vm, super->kind == KIND);                          \
}                                                                              \
                                                                               \
static value_t _##Prefix##_safe_cast(vm_t vm, value_t self, type_t to) {       \
  if (!_is_integer_kind(to->kind))                                             \
    return create_error_value(vm,                                              \
        "cannot safe_cast %s to '%s'", NAME, to->name);                        \
  if (to == value_get_type(self)) return self;                                 \
  if (value_is_shadow(self))                                                   \
    return vm_create_value_shadow(vm, to, NULL, true);                         \
  return _int_coerce(vm, self, to);                                            \
}                                                                              \
                                                                               \
static value_t _const_##Prefix##_safe_cast(vm_t vm, value_t self, type_t to) {\
  if (!_is_integer_kind(to->kind))                                             \
    return create_error_value(vm,                                              \
        "cannot safe_cast const %s to '%s'", NAME, to->name);                  \
  if (to->mut)                                                                 \
    return create_error_value(vm,                                              \
        "cannot safe_cast const %s to %s", NAME, NAME);                        \
  if (to == value_get_type(self)) return self;                                 \
  if (value_is_shadow(self))                                                   \
    return vm_create_value_shadow(vm, to, NULL, true);                         \
  return _int_coerce(vm, self, to);                                            \
}                                                                              \
                                                                               \
static value_t _##Prefix##_assignment(vm_t vm, value_t lvalue, value_t rvalue) {\
  type_t lt = value_get_type(lvalue);                                          \
  type_t rt = value_get_type(rvalue);                                          \
  if (!_is_integer_kind(rt->kind))                                             \
    return create_error_value(vm,                                              \
        "cannot assign '%s' to '%s'", rt->name, lt->name);                     \
  if (value_is_shadow(lvalue) || value_is_shadow(rvalue)) {                    \
    value_set_initialized(lvalue, true);                                       \
    return create_void_value(vm);                                              \
  }                                                                            \
  uint64_t val = _int_read_u64(rvalue);                                       \
  _int_write_u64(lt, value_get_data(lvalue), val);                             \
  value_set_initialized(lvalue, true);                                         \
  return create_void_value(vm);                                                \
}

DEFINE_SINT_VTABLE(i8,  int8_t,  TYPE_KIND_I8,  1, 1, "i8")
DEFINE_SINT_VTABLE(i16, int16_t, TYPE_KIND_I16, 2, 2, "i16")
DEFINE_SINT_VTABLE(i32, int32_t, TYPE_KIND_I32, 4, 4, "i32")
DEFINE_SINT_VTABLE(i64, int64_t, TYPE_KIND_I64, 8, 8, "i64")

/* Unsigned types reuse the same equal/safe_cast/assignment pattern */
#define DEFINE_UINT_VTABLE(Prefix, ctype, KIND, SIZE, ALIGN, NAME)            \
                                                                               \
static value_t _##Prefix##_equal(vm_t vm, value_t a, value_t b) {             \
  type_t ta = value_get_type(a);                                               \
  type_t tb = value_get_type(b);                                               \
  if (!_is_integer_kind(tb->kind))                                             \
    return create_error_value(vm, "cannot compare values of different kinds");  \
  if (value_is_shadow(a) || value_is_shadow(b)) {                              \
    type_t rt = _int_common_type(ta, tb);                                      \
    return vm_create_value_shadow(vm, rt, NULL, true);                         \
  }                                                                            \
  value_t pa, pb;                                                              \
  type_t rt = _int_promote(vm, a, b, &pa, &pb);                               \
  if (!rt) return create_error_value(vm, "integer comparison failed");         \
  return create_bool_value(vm, _int_read_u64(pa) == _int_read_u64(pb));       \
}                                                                              \
                                                                               \
static value_t _##Prefix##_type_equal(vm_t vm, type_t a, type_t b) {          \
  (void)a;                                                                     \
  if (b->kind == TYPE_KIND_WILDCARD)                                           \
    return create_bool_value(vm, true);                                        \
  return create_bool_value(vm, b->kind == KIND);                              \
}                                                                               \
                                                                               \
static value_t _##Prefix##_type_extends(vm_t vm, type_t sub, type_t super) {  \
  (void)sub;                                                                   \
  if (super->kind == TYPE_KIND_WILDCARD)                                       \
    return create_bool_value(vm, true);                                        \
  return create_bool_value(vm, super->kind == KIND);                          \
}                                                                              \
                                                                               \
static value_t _##Prefix##_safe_cast(vm_t vm, value_t self, type_t to) {       \
  if (!_is_integer_kind(to->kind))                                             \
    return create_error_value(vm,                                              \
        "cannot safe_cast %s to '%s'", NAME, to->name);                        \
  if (to == value_get_type(self)) return self;                                 \
  if (value_is_shadow(self))                                                   \
    return vm_create_value_shadow(vm, to, NULL, true);                         \
  return _int_coerce(vm, self, to);                                            \
}                                                                              \
                                                                               \
static value_t _const_##Prefix##_safe_cast(vm_t vm, value_t self, type_t to) {\
  if (!_is_integer_kind(to->kind))                                             \
    return create_error_value(vm,                                              \
        "cannot safe_cast const %s to '%s'", NAME, to->name);                  \
  if (to->mut)                                                                 \
    return create_error_value(vm,                                              \
        "cannot safe_cast const %s to %s", NAME, NAME);                        \
  if (to == value_get_type(self)) return self;                                 \
  if (value_is_shadow(self))                                                   \
    return vm_create_value_shadow(vm, to, NULL, true);                         \
  return _int_coerce(vm, self, to);                                            \
}                                                                              \
                                                                               \
static value_t _##Prefix##_assignment(vm_t vm, value_t lvalue, value_t rvalue) {\
  type_t lt = value_get_type(lvalue);                                          \
  type_t rt = value_get_type(rvalue);                                          \
  if (!_is_integer_kind(rt->kind))                                             \
    return create_error_value(vm,                                              \
        "cannot assign '%s' to '%s'", rt->name, lt->name);                     \
  if (value_is_shadow(lvalue) || value_is_shadow(rvalue)) {                    \
    value_set_initialized(lvalue, true);                                       \
    return create_void_value(vm);                                              \
  }                                                                            \
  uint64_t val = _int_read_u64(rvalue);                                       \
  _int_write_u64(lt, value_get_data(lvalue), val);                             \
  value_set_initialized(lvalue, true);                                         \
  return create_void_value(vm);                                                \
}

DEFINE_UINT_VTABLE(u8,  uint8_t,  TYPE_KIND_U8,  1, 1, "u8")
DEFINE_UINT_VTABLE(u16, uint16_t, TYPE_KIND_U16, 2, 2, "u16")
DEFINE_UINT_VTABLE(u32, uint32_t, TYPE_KIND_U32, 4, 4, "u32")
DEFINE_UINT_VTABLE(u64, uint64_t, TYPE_KIND_U64, 8, 8, "u64")

/* ==================================================================
 * Shared arithmetic/bitwise/relational/shift/unary implementations
 * All integer types (signed + unsigned) point to these same functions.
 * ================================================================== */

static value_t _int_add(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator +: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  return _int_alloc_result(vm, rt, _int_read_u64(pa) + _int_read_u64(pb));
}

static value_t _int_sub(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator -: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  return _int_alloc_result(vm, rt, _int_read_u64(pa) - _int_read_u64(pb));
}

static value_t _int_mul(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator *: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  return _int_alloc_result(vm, rt, _int_read_u64(pa) * _int_read_u64(pb));
}

static value_t _int_div(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator /: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  value_t err = _int_check_zero(vm, pb);
  if (err) return err;
  /* signed or unsigned division depending on result type */
  if (_is_signed_type(rt))
    return _int_alloc_result(vm, rt,
        (uint64_t)((int64_t)_int_read_u64(pa) / (int64_t)_int_read_u64(pb)));
  else
    return _int_alloc_result(vm, rt, _int_read_u64(pa) / _int_read_u64(pb));
}

static value_t _int_mod(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator %%: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  value_t err = _int_check_zero(vm, pb);
  if (err) return err;
  if (_is_signed_type(rt))
    return _int_alloc_result(vm, rt,
        (uint64_t)((int64_t)_int_read_u64(pa) % (int64_t)_int_read_u64(pb)));
  else
    return _int_alloc_result(vm, rt, _int_read_u64(pa) % _int_read_u64(pb));
}

static value_t _int_band(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator &: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  return _int_alloc_result(vm, rt, _int_read_u64(pa) & _int_read_u64(pb));
}

static value_t _int_bor(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator |: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  return _int_alloc_result(vm, rt, _int_read_u64(pa) | _int_read_u64(pb));
}

static value_t _int_bxor(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator ^: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  return _int_alloc_result(vm, rt, _int_read_u64(pa) ^ _int_read_u64(pb));
}

static value_t _int_bnot(vm_t vm, value_t a) {
  type_t ta = value_get_type(a);
  if (value_is_shadow(a))
    return vm_create_value_shadow(vm, ta, NULL, true);
  return _int_alloc_result(vm, ta, ~_int_read_u64(a));
}

static value_t _int_lnot(vm_t vm, value_t a) {
  if (value_is_shadow(a))
    return vm_create_value_shadow(vm, value_get_type(a), NULL, true);
  return create_bool_value(vm, _int_read_u64(a) == 0);
}

static value_t _int_shl(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator <<: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  return _int_alloc_result(vm, rt, _int_read_u64(pa) << _int_read_u64(pb));
}

static value_t _int_shr(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator >>: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  /* signed → arithmetic shift; unsigned → logical shift */
  if (_is_signed_type(rt))
    return _int_alloc_result(vm, rt,
        (uint64_t)((int64_t)_int_read_u64(pa) >> (int64_t)_int_read_u64(pb)));
  else
    return _int_alloc_result(vm, rt, _int_read_u64(pa) >> _int_read_u64(pb));
}

static value_t _int_pos(vm_t vm, value_t a) {
  if (value_is_shadow(a))
    return vm_create_value_shadow(vm, value_get_type(a), NULL, true);
  return _int_alloc_result(vm, value_get_type(a), _int_read_u64(a));
}

static value_t _int_neg(vm_t vm, value_t a) {
  if (value_is_shadow(a))
    return vm_create_value_shadow(vm, value_get_type(a), NULL, true);
  /* two's complement negation works for both signed and unsigned */
  return _int_alloc_result(vm, value_get_type(a),
      (uint64_t)(-(int64_t)_int_read_u64(a)));
}

static value_t _int_gt(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator >: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  if (_is_signed_type(rt))
    return create_bool_value(vm, (int64_t)_int_read_u64(pa) > (int64_t)_int_read_u64(pb));
  else
    return create_bool_value(vm, _int_read_u64(pa) > _int_read_u64(pb));
}

static value_t _int_lt(vm_t vm, value_t a, value_t b) {
  value_t pa, pb;
  type_t rt = _int_promote(vm, a, b, &pa, &pb);
  if (!rt) return create_error_value(vm, "operator <: incompatible integer types");
  if (value_is_shadow(a) || value_is_shadow(b))
    return vm_create_value_shadow(vm, rt, NULL, true);
  if (_is_signed_type(rt))
    return create_bool_value(vm, (int64_t)_int_read_u64(pa) < (int64_t)_int_read_u64(pb));
  else
    return create_bool_value(vm, _int_read_u64(pa) < _int_read_u64(pb));
}

/* ---- Integer to_string ---- */

static value_t _int_to_string(vm_t vm, value_t self) {
  if (value_is_shadow(self))
    return vm_create_value_shadow(vm,
        (type_t)value_get_data(vm_get_str_type(vm)), NULL, true);
  type_t t = value_get_type(self);
  uint64_t val = _int_read_u64(self);
  char buf[32];
  if (_is_signed_kind(t->kind))
    snprintf(buf, sizeof(buf), "%lld", (long long)(int64_t)val);
  else
    snprintf(buf, sizeof(buf), "%llu", (unsigned long long)val);
  return create_str_value(vm, buf);
}

/* ==================================================================
 * Static type singletons — vtables point to shared functions
 * ================================================================== */

#define DEFINE_SINT_TYPE(Prefix, ctype, KIND, SIZE, ALIGN, NAME)              \
type_t type_get_##Prefix##_type(allocator_t allocator) {                       \
  (void)allocator;                                                             \
  static struct _type_t t = {                                                  \
      .kind  = KIND,                                                           \
      .name  = (char *)NAME,                                                   \
      .size  = SIZE,                                                           \
      .align = ALIGN,                                                          \
      .mut   = true,                                                           \
      .vtable = {                                                              \
          .clone        = _int_clone,                                          \
          .equal        = _##Prefix##_equal,                                   \
          .extends      = NULL,                                                \
          .type_equal   = _##Prefix##_type_equal,                              \
          .type_extends = _##Prefix##_type_extends,                            \
          .band         = _int_band,                                           \
          .bor          = _int_bor,                                            \
          .bxor         = _int_bxor,                                           \
          .bnot         = _int_bnot,                                           \
          .lnot         = _int_lnot,                                           \
          .add          = _int_add,                                            \
          .sub          = _int_sub,                                            \
          .mul          = _int_mul,                                            \
          .div          = _int_div,                                            \
          .mod          = _int_mod,                                            \
          .shl          = _int_shl,                                            \
          .shr          = _int_shr,                                            \
          .pos          = _int_pos,                                            \
          .neg          = _int_neg,                                            \
          .gt           = _int_gt,                                             \
          .lt           = _int_lt,                                             \
          .safe_cast    = _##Prefix##_safe_cast,                               \
          .assignment   = _##Prefix##_assignment,                              \
          .to_string    = _int_to_string,                                      \
      },                                                                       \
  };                                                                           \
  return &t;                                                                   \
}                                                                              \
                                                                               \
type_t type_get_const_##Prefix##_type(allocator_t allocator) {                 \
  (void)allocator;                                                             \
  static struct _type_t t = {                                                  \
      .kind  = KIND,                                                           \
      .name  = (char *)"const " NAME,                                          \
      .size  = SIZE,                                                           \
      .align = ALIGN,                                                          \
      .mut   = false,                                                          \
      .vtable = {                                                              \
          .clone        = _int_clone,                                          \
          .equal        = _##Prefix##_equal,                                   \
          .extends      = NULL,                                                \
          .type_equal   = _##Prefix##_type_equal,                              \
          .type_extends = _##Prefix##_type_extends,                            \
          .band         = _int_band,                                           \
          .bor          = _int_bor,                                            \
          .bxor         = _int_bxor,                                           \
          .bnot         = _int_bnot,                                           \
          .lnot         = _int_lnot,                                           \
          .add          = _int_add,                                            \
          .sub          = _int_sub,                                            \
          .mul          = _int_mul,                                            \
          .div          = _int_div,                                            \
          .mod          = _int_mod,                                            \
          .shl          = _int_shl,                                            \
          .shr          = _int_shr,                                            \
          .pos          = _int_pos,                                            \
          .neg          = _int_neg,                                            \
          .gt           = _int_gt,                                             \
          .lt           = _int_lt,                                             \
          .safe_cast    = _const_##Prefix##_safe_cast,                         \
          .assignment   = NULL,                                                \
          .to_string    = _int_to_string,                                      \
      },                                                                       \
  };                                                                           \
  return &t;                                                                   \
}                                                                              \
                                                                               \
value_t create_##Prefix##_value(vm_t vm, ctype val) {                          \
  allocator_t alloc = vm_get_allocator(vm);                                    \
  ctype *data = (ctype *)allocator_alloc(alloc, SIZE);                         \
  *data = val;                                                                 \
  type_t t = (type_t)value_get_data(vm_get_##Prefix##_type(vm));               \
  value_t v = value_create(alloc, t, data, true);                              \
  scope_t scope = vm_get_current_scope(vm);                                    \
  if (scope) { vec_push(scope->values, v); }                                   \
  return v;                                                                    \
}

#define DEFINE_UINT_TYPE(Prefix, ctype, KIND, SIZE, ALIGN, NAME)               \
type_t type_get_##Prefix##_type(allocator_t allocator) {                       \
  (void)allocator;                                                             \
  static struct _type_t t = {                                                  \
      .kind  = KIND,                                                           \
      .name  = (char *)NAME,                                                   \
      .size  = SIZE,                                                           \
      .align = ALIGN,                                                          \
      .mut   = true,                                                           \
      .vtable = {                                                              \
          .clone        = _int_clone,                                          \
          .equal        = _##Prefix##_equal,                                   \
          .extends      = NULL,                                                \
          .type_equal   = _##Prefix##_type_equal,                              \
          .type_extends = _##Prefix##_type_extends,                            \
          .band         = _int_band,                                           \
          .bor          = _int_bor,                                            \
          .bxor         = _int_bxor,                                           \
          .bnot         = _int_bnot,                                           \
          .lnot         = _int_lnot,                                           \
          .add          = _int_add,                                            \
          .sub          = _int_sub,                                            \
          .mul          = _int_mul,                                            \
          .div          = _int_div,                                            \
          .mod          = _int_mod,                                            \
          .shl          = _int_shl,                                            \
          .shr          = _int_shr,                                            \
          .pos          = _int_pos,                                            \
          .neg          = _int_neg,                                            \
          .gt           = _int_gt,                                             \
          .lt           = _int_lt,                                             \
          .safe_cast    = _##Prefix##_safe_cast,                               \
          .assignment   = _##Prefix##_assignment,                              \
          .to_string    = _int_to_string,                                      \
      },                                                                       \
  };                                                                           \
  return &t;                                                                   \
}                                                                              \
                                                                               \
type_t type_get_const_##Prefix##_type(allocator_t allocator) {                 \
  (void)allocator;                                                             \
  static struct _type_t t = {                                                  \
      .kind  = KIND,                                                           \
      .name  = (char *)"const " NAME,                                          \
      .size  = SIZE,                                                           \
      .align = ALIGN,                                                          \
      .mut   = false,                                                          \
      .vtable = {                                                              \
          .clone        = _int_clone,                                          \
          .equal        = _##Prefix##_equal,                                   \
          .extends      = NULL,                                                \
          .type_equal   = _##Prefix##_type_equal,                              \
          .type_extends = _##Prefix##_type_extends,                            \
          .band         = _int_band,                                           \
          .bor          = _int_bor,                                            \
          .bxor         = _int_bxor,                                           \
          .bnot         = _int_bnot,                                           \
          .lnot         = _int_lnot,                                           \
          .add          = _int_add,                                            \
          .sub          = _int_sub,                                            \
          .mul          = _int_mul,                                            \
          .div          = _int_div,                                            \
          .mod          = _int_mod,                                            \
          .shl          = _int_shl,                                            \
          .shr          = _int_shr,                                            \
          .pos          = _int_pos,                                            \
          .neg          = _int_neg,                                            \
          .gt           = _int_gt,                                             \
          .lt           = _int_lt,                                             \
          .safe_cast    = _const_##Prefix##_safe_cast,                         \
          .assignment   = NULL,                                                \
          .to_string    = _int_to_string,                                      \
      },                                                                       \
  };                                                                           \
  return &t;                                                                   \
}                                                                              \
                                                                               \
value_t create_##Prefix##_value(vm_t vm, ctype val) {                          \
  allocator_t alloc = vm_get_allocator(vm);                                    \
  ctype *data = (ctype *)allocator_alloc(alloc, SIZE);                         \
  *data = val;                                                                 \
  type_t t = (type_t)value_get_data(vm_get_##Prefix##_type(vm));               \
  value_t v = value_create(alloc, t, data, true);                              \
  scope_t scope = vm_get_current_scope(vm);                                    \
  if (scope) { vec_push(scope->values, v); }                                   \
  return v;                                                                    \
}

DEFINE_SINT_TYPE(i8,  int8_t,  TYPE_KIND_I8,  1, 1, "i8")
DEFINE_SINT_TYPE(i16, int16_t, TYPE_KIND_I16, 2, 2, "i16")
DEFINE_SINT_TYPE(i32, int32_t, TYPE_KIND_I32, 4, 4, "i32")
DEFINE_SINT_TYPE(i64, int64_t, TYPE_KIND_I64, 8, 8, "i64")

DEFINE_UINT_TYPE(u8,  uint8_t,  TYPE_KIND_U8,  1, 1, "u8")
DEFINE_UINT_TYPE(u16, uint16_t, TYPE_KIND_U16, 2, 2, "u16")
DEFINE_UINT_TYPE(u32, uint32_t, TYPE_KIND_U32, 4, 4, "u32")
DEFINE_UINT_TYPE(u64, uint64_t, TYPE_KIND_U64, 8, 8, "u64")
