#include "c/lower.h"
#include "c/c_ir.h"
#include "c/c_type.h"
#include "c/mangle.h"
#include "c/c_ir_unit.h"
#include "c/c_ir_function.h"
#include "c/c_ir_variable.h"
#include "c/c_ir_enum.h"
#include "c/c_ir_typedef.h"
#include "c/c_ir_forward_decl.h"
#include "c/c_ir_include.h"
#include "c/c_ir_stmt_block.h"
#include "c/c_ir_stmt_return.h"
#include "c/c_ir_expr_literal.h"
#include "c/c_ir_expr_call.h"
#include "c/c_ir_expr_compound.h"
#include "c/c_ir_expr_cast.h"
#include "c/c_ir_expr_initializer.h"
#include "cubec/node.h"
#include "cubec/statement_function.h"
#include "cubec/statement_defer.h"
#include "cubec/function_argument.h"
#include "cubec/literal_identifier.h"
#include "engine/semantic_type.h"
#include "engine/symbol.h"
#include "engine/scope.h"
#include "engine/context.h"
#include "engine/runtime_collection.h"
#include "core/node.h"
#include <string.h>

/* Forward declarations (defined in lower_expr.c and lower_stmt.c) */
c_type_t lower_type(allocator_t allocator, semantic_type_t type,
                     const char *module_hash, c_ir_unit_t unit);
c_ir_node_t lower_expr(allocator_t allocator, context_t ctx, node_t node,
                        const char *module_hash, c_ir_unit_t unit);
c_ir_node_t lower_stmt(allocator_t allocator, context_t ctx, node_t node,
                        const char *module_hash, vec_t defer_stack, c_ir_unit_t unit);

/* ===== Type name helper ===== */

/**
 * @brief Get the mangled C type name for a semantic type.
 *
 * For named types: uses mangle_name(module_hash, name).
 * For anonymous types: uses the name generated by lower_type (which already
 * includes the module_hash prefix).
 */
static string_t get_c_type_name(allocator_t allocator, semantic_type_t type,
                                  const char *module_hash, c_ir_unit_t unit) {
  const char *name = semantic_type_get_name(type);
  if (name) {
    return mangle_name(allocator, module_hash, name);
  }

  /* Anonymous type: lower_type already generates a name with module_hash prefix.
   * Extract it from the c_type_t. */
  c_type_t c_type = lower_type(allocator, type, module_hash, unit);
  string_t result = allocator_create(allocator, &g_string_type,
                                      &(string_init_t){.str = string_get(c_type->left)});
  c_type_dispose(allocator, &c_type);
  return result;
}

/* ===== Type emission helpers ===== */

static void emit_type_forward_decl(allocator_t allocator, semantic_type_t type,
                                     c_ir_unit_t unit, const char *module_hash) {
  enum type_kind kind = semantic_type_get_kind(type);

  /* Only composite types need forward declarations */
  if (kind != TYPE_STRUCT && kind != TYPE_UNION && kind != TYPE_CUNION &&
      kind != TYPE_SLICE && kind != TYPE_TUPLE && kind != TYPE_GENERIC_INSTANCE) {
    return;
  }

  string_t mangled = get_c_type_name(allocator, type, module_hash, unit);
  location_t null_loc = {0};
  c_ir_node_t fwd = (c_ir_node_t)c_ir_forward_decl_create(
      allocator, string_get(mangled), null_loc);
  vec_push(unit->forward_decls, fwd);
  allocator_free(allocator, &mangled);
}

static void emit_type_typedef(allocator_t allocator, semantic_type_t type,
                                c_ir_unit_t unit, const char *module_hash) {
  enum type_kind kind = semantic_type_get_kind(type);

  if (kind != TYPE_STRUCT && kind != TYPE_UNION && kind != TYPE_CUNION &&
      kind != TYPE_SLICE && kind != TYPE_TUPLE && kind != TYPE_GENERIC_INSTANCE) {
    return;
  }

  string_t mangled = get_c_type_name(allocator, type, module_hash, unit);

  /* Build the underlying C type */
  c_type_t c_type;
  if (kind == TYPE_STRUCT || kind == TYPE_UNION || kind == TYPE_CUNION) {
    /* Self-referencing typedef: typedef struct m3a7_X m3a7_X */
    c_type = c_type_primitive(allocator, string_get(mangled));
  } else {
    c_type = lower_type(allocator, type, module_hash, unit);
  }

  location_t null_loc = {0};
  c_ir_node_t td = (c_ir_node_t)c_ir_typedef_create(
      allocator, c_type, string_get(mangled), null_loc);
  vec_push(unit->typedefs, td);
  allocator_free(allocator, &mangled);
}

static void emit_struct_body(allocator_t allocator, semantic_type_t type,
                               c_ir_unit_t unit, const char *module_hash) {
  type_impl_t impl = semantic_type_get_impl(type);
  enum type_kind kind = semantic_type_get_kind(type);
  vec_t fields = NULL;

  if (kind == TYPE_STRUCT || kind == TYPE_UNION || kind == TYPE_CUNION) {
    fields = impl->struct_type.fields;
  } else if (kind == TYPE_GENERIC_INSTANCE) {
    fields = impl->generic_instance.fields;
  } else if (kind == TYPE_TUPLE) {
    fields = impl->tuple.fields;
  }

  string_t body;

  if (kind == TYPE_SLICE) {
    /* Slice: generate struct body with ptr/start/length */
    c_type_t elem_c_type = lower_type(allocator, impl->slice.element, module_hash, unit);
    body = allocator_create(allocator, &g_string_type,
                            &(string_init_t){.str = ""});
    string_concat(body, string_get(elem_c_type->left));
    if (elem_c_type->right && strlen(string_get(elem_c_type->right)) > 0) {
      string_concat(body, " ");
      string_concat(body, string_get(elem_c_type->right));
    }
    string_concat(body, "* ptr;\n    size_t start;\n    size_t length;\n");
    c_type_dispose(allocator, &elem_c_type);
  } else if (fields && vec_get_size(fields) > 0) {
    body = allocator_create(allocator, &g_string_type,
                            &(string_init_t){.str = ""});
    size_t count = vec_get_size(fields);
    for (size_t i = 0; i < count; i++) {
      struct symbol *field = vec_get(fields, i);
      if (!field->field.type) continue;
      c_type_t c_type = lower_type(allocator, field->field.type, module_hash, unit);
      string_concat(body, string_get(c_type->left));
      if (c_type->right && strlen(string_get(c_type->right)) > 0) {
        string_concat(body, " ");
        string_concat(body, string_get(c_type->right));
      }
      string_concat(body, " ");
      string_concat(body, field->name);
      string_concat(body, ";\n    ");
      c_type_dispose(allocator, &c_type);
    }
  } else {
    /* Empty struct or no fields — nothing to emit */
    return;
  }

  string_t mangled = get_c_type_name(allocator, type, module_hash, unit);
  location_t null_loc = {0};
  c_ir_node_t sd = (c_ir_node_t)c_ir_forward_decl_create_with_body(
      allocator, string_get(mangled), string_get(body), null_loc);
  vec_push(unit->struct_defs, sd);
  allocator_free(allocator, &body);
  allocator_free(allocator, &mangled);
}

static void emit_enum_def(allocator_t allocator, semantic_type_t type,
                            c_ir_unit_t unit, const char *module_hash) {
  enum type_kind kind = semantic_type_get_kind(type);
  if (kind != TYPE_ENUM) return;

  const char *name = semantic_type_get_name(type);
  if (!name) return;

  type_impl_t impl = semantic_type_get_impl(type);
  string_t mangled = mangle_name(allocator, module_hash, name);

  c_type_t backing = impl->enum_type.backing_type
      ? lower_type(allocator, impl->enum_type.backing_type, module_hash, unit)
      : NULL;

  vec_t items = allocator_create(allocator, &g_vec_type,
                                   &(vec_init_t){.auto_dispose = false});
  size_t item_count = impl->enum_type.items
      ? vec_get_size(impl->enum_type.items) : 0;
  for (size_t j = 0; j < item_count; j++) {
    struct symbol *item_sym = vec_get(impl->enum_type.items, j);
    string_t item_name = mangle_enum_item(allocator, module_hash, name, item_sym->name);
    char val_buf[32];
    snprintf(val_buf, sizeof(val_buf), "%lld", item_sym->enum_item.value);
    c_ir_enum_item_t ei = c_ir_enum_item_create(allocator,
                                                  string_get(item_name), val_buf);
    vec_push(items, ei);
    allocator_free(allocator, &item_name);
  }

  location_t null_loc = {0};
  c_ir_node_t enum_def = (c_ir_node_t)c_ir_enum_def_create(
      allocator, string_get(mangled), backing, items, null_loc);
  vec_push(unit->enum_defs, enum_def);
  allocator_free(allocator, &mangled);
}

/* ===== Function emission helpers ===== */

static vec_t build_param_list(allocator_t allocator, struct symbol *sym,
                                const char *module_hash, c_ir_unit_t unit) {
  if (!sym->function.type) return NULL;
  type_impl_t impl = semantic_type_get_impl(sym->function.type);

  vec_t params = allocator_create(allocator, &g_vec_type,
                                   &(vec_init_t){.auto_dispose = false});
  size_t param_count = impl->function.params
      ? vec_get_size(impl->function.params) : 0;

  cubec_statement_function_t fn_ast =
      (cubec_statement_function_t)sym->function.ast_node;

  for (size_t j = 0; j < param_count; j++) {
    semantic_type_t param_type = vec_get(impl->function.params, j);
    c_type_t c_type = lower_type(allocator, param_type, module_hash, unit);
    const char *param_name = "_";
    if (fn_ast && fn_ast->arguments && j < vec_get_size(fn_ast->arguments)) {
      cubec_function_argument_t arg = vec_get(fn_ast->arguments, j);
      if (arg->identifier) {
        cubec_literal_identifier_t id = (cubec_literal_identifier_t)arg->identifier;
        param_name = string_get(id->value);
      }
    }
    c_ir_param_t p = c_ir_param_create(allocator, c_type, param_name);
    vec_push(params, p);
  }
  return params;
}

static void emit_function_proto(allocator_t allocator, struct symbol *sym,
                                  c_ir_unit_t unit, const char *module_hash) {
  if (!sym->function.type) return;
  type_impl_t impl = semantic_type_get_impl(sym->function.type);

  vec_t params = build_param_list(allocator, sym, module_hash, unit);
  c_type_t ret_type = lower_type(allocator, impl->function.return_type, module_hash, unit);

  cubec_statement_function_t fn_ast =
      (cubec_statement_function_t)sym->function.ast_node;
  bool is_extern = fn_ast ? fn_ast->is_extern : false;
  bool is_c_variadic = fn_ast ? fn_ast->is_c_variadic : false;
  bool is_export = sym->is_export;

  const char *func_name;
  string_t mangled;
  if (is_extern) {
    func_name = sym->name;
    mangled = NULL;
  } else {
    mangled = mangle_name(allocator, module_hash, sym->name);
    func_name = string_get(mangled);
  }

  if (is_export) {
    /* Export functions (including export extern) → declaration in .h */
    c_ir_node_t decl = (c_ir_node_t)c_ir_function_decl_create(
        allocator, ret_type, func_name, params,
        false, false, false, false, is_c_variadic, sym->location);
    vec_push(unit->function_decls, decl);
  } else if (is_extern) {
    /* Non-export extern → declaration in .c only */
    c_ir_node_t decl = (c_ir_node_t)c_ir_function_decl_create(
        allocator, ret_type, func_name, params,
        false, false, false, false, is_c_variadic, sym->location);
    vec_push(unit->extern_decls, decl);
  }

  if (mangled) allocator_free(allocator, &mangled);
}

static void emit_function_def(allocator_t allocator, context_t ctx, struct symbol *sym,
                                c_ir_unit_t unit, const char *module_hash) {
  if (!sym->function.type) return;
  type_impl_t impl = semantic_type_get_impl(sym->function.type);

  cubec_statement_function_t fn_ast =
      (cubec_statement_function_t)sym->function.ast_node;
  if (!fn_ast || !fn_ast->body) return;

  vec_t params = build_param_list(allocator, sym, module_hash, unit);
  c_type_t ret_type = lower_type(allocator, impl->function.return_type, module_hash, unit);

  bool is_extern = fn_ast->is_extern;
  bool is_c_variadic = fn_ast->is_c_variadic;
  bool is_export = sym->is_export;
  bool is_inline = fn_ast->is_inline;

  const char *func_name;
  string_t mangled;
  if (is_extern) {
    func_name = sym->name;
    mangled = NULL;
  } else {
    mangled = mangle_name(allocator, module_hash, sym->name);
    func_name = string_get(mangled);
  }

  /* Create defer stack for this function */
  vec_t defer_stack = allocator_create(allocator, &g_vec_type,
                                         &(vec_init_t){.auto_dispose = false});

  /* Set up scope for function body — create a child scope from global,
   * register parameter symbols so that scope_lookup can find them. */
  scope_t saved_scope = ctx->current_scope;
  ctx->current_scope = scope_create(ctx->allocator, ctx->global_scope,
                                     SCOPE_FUNCTION, sym->location);
  vec_push(ctx->all_scopes, ctx->current_scope);

  /* Register function parameters as variables in the function scope */
  if (fn_ast->arguments) {
    size_t arg_count = vec_get_size(fn_ast->arguments);
    for (size_t a = 0; a < arg_count; a++) {
      cubec_function_argument_t arg = vec_get(fn_ast->arguments, a);
      if (arg->identifier) {
        const char *param_name = string_get(
            ((cubec_literal_identifier_t)arg->identifier)->value);
        struct symbol *param_sym = scope_lookup(ctx->global_scope, param_name);
        if (param_sym) {
          scope_push_symbol(ctx->current_scope, param_sym);
        }
      }
    }
  }

  /* Lower function body */
  c_ir_node_t body = lower_stmt(allocator, ctx, fn_ast->body, module_hash, defer_stack, unit);

  /* Restore scope */
  ctx->current_scope = saved_scope;

  /* Append deferred cleanup at end of function body (LIFO order) */
  size_t defer_count = vec_get_size(defer_stack);
  if (defer_count > 0 && body && c_ir_get_kind(body) == C_IR_STMT_BLOCK) {
    c_ir_stmt_block_t block = (c_ir_stmt_block_t)body;
    for (size_t d = defer_count; d > 0; d--) {
      node_t defer_node = vec_get(defer_stack, d - 1);
      cubec_statement_defer_t df = (cubec_statement_defer_t)defer_node;
      c_ir_node_t defer_body = lower_stmt(allocator, ctx, df->body, module_hash, NULL, unit);
      if (defer_body) vec_push(block->statements, defer_body);
    }
  }
  allocator_free(allocator, &defer_stack);

  c_ir_node_t def = (c_ir_node_t)c_ir_function_def_create(
      allocator, ret_type, func_name, params,
      !is_export, is_inline, false, false, is_c_variadic, body, sym->location);
  vec_push(unit->function_defs, def);

  if (mangled) allocator_free(allocator, &mangled);
}

static void emit_variable_decl(allocator_t allocator, struct symbol *sym,
                                 c_ir_unit_t unit, const char *module_hash) {
  if (!sym->variable.type) return;

  c_type_t c_type = lower_type(allocator, sym->variable.type, module_hash, unit);
  if (!sym->variable.is_mutable) c_type_const(allocator, c_type);

  string_t mangled = mangle_name(allocator, module_hash, sym->name);
  c_ir_node_t vd = (c_ir_node_t)c_ir_variable_decl_create(
      allocator, c_type, string_get(mangled),
      NULL,   /* init — TODO: from AST */
      !sym->is_export,  /* is_static */
      false,  /* is_extern */
      sym->location);
  vec_push(unit->variable_decls, vd);
  allocator_free(allocator, &mangled);
}

/* ===== Main entry point ===== */

/**
 * @brief Lower the program AST into a C IR compilation unit.
 */
c_ir_unit_t lower_program(allocator_t allocator, context_t ctx, node_t program,
                           bool generate_executable) {
  if (!program || program->kind != CUBEC_NODE_PROGRAM) return NULL;

  /* Compute module hash from filename */
  const char *filename = ctx->current_file ? ctx->current_file : "unknown";
  string_t module_hash_str = mangle_module_hash(allocator, filename);
  const char *module_hash = string_get(module_hash_str);

  /* Create the compilation unit */
  location_t loc = program->location;
  c_ir_unit_t unit = c_ir_unit_create(allocator, filename, module_hash, loc);

  /* Add standard includes */
  c_ir_node_t stdint_h = (c_ir_node_t)c_ir_include_create(
      allocator, "stdint.h", true, loc);
  vec_push(unit->includes, stdint_h);
  c_ir_node_t stdbool_h = (c_ir_node_t)c_ir_include_create(
      allocator, "stdbool.h", true, loc);
  vec_push(unit->includes, stdbool_h);
  c_ir_node_t stdlib_h = (c_ir_node_t)c_ir_include_create(
      allocator, "stdlib.h", true, loc);
  vec_push(unit->includes, stdlib_h);
  c_ir_node_t stdio_h = (c_ir_node_t)c_ir_include_create(
      allocator, "stdio.h", true, loc);
  vec_push(unit->includes, stdio_h);

  runtime_collection_t rc = ctx->runtime;

  /* Step 1: Forward declarations for all composite types */
  size_t type_count = vec_get_size(rc->runtime_types);
  for (size_t i = 0; i < type_count; i++) {
    semantic_type_t type = vec_get(rc->runtime_types, i);
    emit_type_forward_decl(allocator, type, unit, module_hash);
  }

  /* Step 2: Typedefs for all composite types */
  for (size_t i = 0; i < type_count; i++) {
    semantic_type_t type = vec_get(rc->runtime_types, i);
    emit_type_typedef(allocator, type, unit, module_hash);
  }

  /* Step 3: Struct body definitions and enum definitions */
  for (size_t i = 0; i < type_count; i++) {
    semantic_type_t type = vec_get(rc->runtime_types, i);
    enum type_kind kind = semantic_type_get_kind(type);
    if (kind == TYPE_ENUM) {
      emit_enum_def(allocator, type, unit, module_hash);
    } else if (kind == TYPE_STRUCT || kind == TYPE_UNION || kind == TYPE_CUNION ||
               kind == TYPE_SLICE || kind == TYPE_TUPLE || kind == TYPE_GENERIC_INSTANCE) {
      emit_struct_body(allocator, type, unit, module_hash);
    }
  }

  /* Step 4: Function prototypes (export → .h, extern → .c only) */
  size_t func_count = vec_get_size(rc->runtime_functions);
  for (size_t i = 0; i < func_count; i++) {
    struct symbol *sym = vec_get(rc->runtime_functions, i);
    emit_function_proto(allocator, sym, unit, module_hash);
  }

  /* Step 5: Global variable declarations */
  size_t var_count = vec_get_size(rc->runtime_variables);
  for (size_t i = 0; i < var_count; i++) {
    struct symbol *sym = vec_get(rc->runtime_variables, i);
    emit_variable_decl(allocator, sym, unit, module_hash);
  }

  /* Step 6: Function definitions (bodies) */
  for (size_t i = 0; i < func_count; i++) {
    struct symbol *sym = vec_get(rc->runtime_functions, i);
    emit_function_def(allocator, ctx, sym, unit, module_hash);
  }

  /* Step 7: Generate C main wrapper for executable */
  if (generate_executable) {
    for (size_t i = 0; i < func_count; i++) {
      struct symbol *sym = vec_get(rc->runtime_functions, i);
      if (sym->kind == SYMBOL_FUNCTION && sym->is_export &&
          strcmp(sym->name, "main") == 0) {
        /* Found exported main — generate C main wrapper */
        string_t mangled_main = mangle_name(allocator, module_hash, "main");

        vec_t main_params = allocator_create(allocator, &g_vec_type,
                                               &(vec_init_t){.auto_dispose = false});
        /* argc: int */
        c_type_t int_type = c_type_primitive(allocator, "int");
        c_ir_param_t argc_p = c_ir_param_create(allocator, int_type, "argc");
        vec_push(main_params, argc_p);
        /* argv: char** */
        c_type_t char_type = c_type_primitive(allocator, "char");
        c_type_t char_ptr = c_type_pointer(allocator, char_type);
        c_type_t char_ptr_ptr = c_type_pointer(allocator, char_ptr);
        c_ir_param_t argv_p = c_ir_param_create(allocator, char_ptr_ptr, "argv");
        vec_push(main_params, argv_p);

        /* Build argument: (slice_str){ .ptr = argv, .start = 0, .length = argc } */
        vec_t init_fields = allocator_create(allocator, &g_vec_type,
                                               &(vec_init_t){.auto_dispose = false});

        /* Cast argv (char**) to const char** to match slice element type */
        c_ir_node_t argv_ident = (c_ir_node_t)c_ir_expr_ident_create(
            allocator, "argv", loc);
        c_type_t const_char_type = c_type_primitive(allocator, "char");
        c_type_t const_char_ptr = c_type_pointer(allocator, const_char_type);
        c_type_const(allocator, const_char_ptr);
        c_type_t const_char_ptr_ptr = c_type_pointer(allocator, const_char_ptr);
        c_ir_node_t argv_cast = (c_ir_node_t)c_ir_expr_cast_create(
            allocator, const_char_ptr_ptr, argv_ident, loc);
        c_ir_node_t init_ptr = (c_ir_node_t)c_ir_expr_initializer_create(
            allocator, "ptr", argv_cast, loc);
        vec_push(init_fields, init_ptr);

        c_ir_node_t zero = (c_ir_node_t)c_ir_expr_numeric_create(
            allocator, "0", loc);
        c_ir_node_t init_start = (c_ir_node_t)c_ir_expr_initializer_create(
            allocator, "start", zero, loc);
        vec_push(init_fields, init_start);

        c_ir_node_t argc_ident = (c_ir_node_t)c_ir_expr_ident_create(
            allocator, "argc", loc);
        c_ir_node_t init_len = (c_ir_node_t)c_ir_expr_initializer_create(
            allocator, "length", argc_ident, loc);
        vec_push(init_fields, init_len);

        /* Slice type from the function's first parameter */
        c_type_t slice_type;
        type_impl_t main_impl = semantic_type_get_impl(sym->function.type);
        if (main_impl->function.params && vec_get_size(main_impl->function.params) > 0) {
          semantic_type_t first_param = vec_get(main_impl->function.params, 0);
          slice_type = lower_type(allocator, first_param, module_hash, unit);
        } else {
          c_type_t fallback_char = c_type_primitive(allocator, "char");
          c_type_t fallback_ptr = c_type_pointer(allocator, fallback_char);
          c_type_const(allocator, fallback_ptr);
          slice_type = fallback_ptr;
        }
        c_ir_node_t slice_compound = (c_ir_node_t)c_ir_expr_compound_create(
            allocator, slice_type, init_fields, loc);

        c_ir_node_t callee = (c_ir_node_t)c_ir_expr_ident_create(
            allocator, string_get(mangled_main), loc);
        vec_t call_args = allocator_create(allocator, &g_vec_type,
                                             &(vec_init_t){.auto_dispose = false});
        vec_push(call_args, slice_compound);
        c_ir_node_t call = (c_ir_node_t)c_ir_expr_call_create(
            allocator, callee, call_args, loc);

        c_ir_node_t ret = (c_ir_node_t)c_ir_stmt_return_create(
            allocator, call, loc);

        vec_t body_stmts = allocator_create(allocator, &g_vec_type,
                                              &(vec_init_t){.auto_dispose = false});
        vec_push(body_stmts, ret);
        c_ir_node_t body = (c_ir_node_t)c_ir_stmt_block_create(
            allocator, body_stmts, loc);

        c_type_t ret_type = c_type_primitive(allocator, "int");
        c_ir_node_t main_def = (c_ir_node_t)c_ir_function_def_create(
            allocator, ret_type, "main", main_params,
            false, false, false, false, false, body, loc);
        vec_push(unit->function_defs, main_def);

        allocator_free(allocator, &mangled_main);
        break;
      }
    }
  }

  allocator_free(allocator, &module_hash_str);
  return unit;
}
