param(
    [Parameter(Mandatory)] [string]$InputFile,
    [Parameter(Mandatory)] [string]$OutputFile,
    [Parameter(Mandatory)] [string]$VarName
)

$bytes = [System.IO.File]::ReadAllBytes($InputFile)
$len = $bytes.Length

$writer = [System.IO.StreamWriter]::new($OutputFile, $false, [System.Text.Encoding]::ASCII)
$writer.WriteLine('/* Auto-generated by cmake/bin_to_c.ps1 - DO NOT EDIT */')
$writer.WriteLine('#include <stddef.h>')
$writer.WriteLine()
$writer.Write("const unsigned char ${VarName}[$len] = {")

$sb = [System.Text.StringBuilder]::new(8192)
for ($i = 0; $i -lt $len; $i++) {
    if ($i % 16 -eq 0) {
        [void]$sb.Append("`n  ")
    }
    [void]$sb.AppendFormat('0x{0:X2}', $bytes[$i])
    if ($i -lt $len - 1) {
        [void]$sb.Append(', ')
    }
    if ($i % 64 -eq 63 -or $i -eq $len - 1) {
        $writer.Write($sb.ToString())
        $sb.Clear()
    }
}

$writer.WriteLine()
$writer.WriteLine('};')
$writer.WriteLine("const size_t ${VarName}_size = ${len};")
$writer.Close()
Write-Host "Generated $OutputFile ($len bytes)"
