param(
    [Parameter(Mandatory)] [string]$InputFile,
    [Parameter(Mandatory)] [string]$OutputFile,
    [Parameter(Mandatory)] [string]$VarName,
    [switch]$Quiet
)

$bytes = [System.IO.File]::ReadAllBytes($InputFile)
$len = $bytes.Length

# Pre-compute hex lookup table (256 entries, done once instead of per-byte AppendFormat)
$hexTable = 0..255 | ForEach-Object { '0x{0:X2}' -f $_ }

# Pre-estimate output size to avoid StringBuilder reallocation
# Each byte → "0xXX" (4 chars) + ", " (2 chars) + newlines/indent overhead
$estimatedSize = $len * 7 + ($len / 16 + 2) * 4 + 256
$sb = [System.Text.StringBuilder]::new([int]$estimatedSize)

for ($i = 0; $i -lt $len; $i++) {
    if ($i % 16 -eq 0) {
        [void]$sb.Append("`n  ")
    }
    [void]$sb.Append($hexTable[$bytes[$i]])
    if ($i -lt $len - 1) {
        [void]$sb.Append(', ')
    }
}

$writer = [System.IO.StreamWriter]::new($OutputFile, $false, [System.Text.Encoding]::ASCII)
$writer.WriteLine('/* Auto-generated by cmake/bin_to_c.ps1 - DO NOT EDIT */')
$writer.WriteLine('#include <stddef.h>')
$writer.WriteLine()
$writer.Write("const unsigned char ${VarName}[$len] = {")
$writer.Write($sb.ToString())
$writer.WriteLine()
$writer.WriteLine('};')
$writer.WriteLine("const size_t ${VarName}_size = ${len};")
$writer.Close()

if (-not $Quiet) {
    Write-Host "Generated $OutputFile ($len bytes)"
}
